name: role_based_app
description: A Flutter role-based application with multiple user types
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  geolocator: ^10.1.0
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  qr_code_tools: ^0.2.0
  image_picker: ^1.0.4
  google_mlkit_barcode_scanning: ^0.14.1
  permission_handler: ^12.0.1
  mobile_scanner: ^3.5.2
  intl: ^0.18.1
  dio: ^5.4.0
  file_picker: ^8.0.0
  shared_preferences: ^2.3.2
  http_parser: ^4.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"